### ISSUE TITLE
Don't toggle switching when only one window open

### ISSUE THREAD

**Issue by andersevenrud** [sindrets/winshift.nvim#1]
Hi,

First of all, thanks for this extension. It's great!

I just noticed that if there's only one window open, I can still enter `WIN MOVE MODE`. Maybe it would be better to just flash a message or something in this case instead of having to press <kbd>q</kbd>/<kbd>ESC</kbd> ?

This is such a minor nitpick detail, so probably doesn't matter at all. But just thought I'd mention it :smile:

**Comment by sindrets** [comment]
Thank you! I'm glad to hear you find it useful!

I'm not really sure I want to do anything about this, because technically it's doing what it's supposed to do. There's just nowhere you can move the window. I mean, there's no motivation for entering Win-Move mode when there's only one window in the current tabpage. 

In short, I feel fine blaming the user for ending up in that state. In general I try to avoid safeguarding pointless states if the means to end up in said state is predictably pointless. In this case: entering a mode for moving windows, when you only have one window, is - in my opinion - predictably pointless.

But maybe I'll change my mind. I'll think about it.

**Comment by andersevenrud** [comment]
> In short, I feel fine blaming the user for ending up in that state.

Yup, and that's perfectly fine.

I ended up there quite a few times, hah. That's what I get for swapping some keybindings around when muscle memory is strong  :joy: 

> But maybe I'll change my mind. I'll think about it.

Feel free to close this.
